
package com.ccf.mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CardImgrecon", targetNamespace = "http://webservice.wintone.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CardImgrecon {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "wjbresult", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.Wjbresult")
    @ResponseWrapper(localName = "wjbresultResponse", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.WjbresultResponse")
    public String wjbresult(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doAllCardReconForUsers", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.DoAllCardReconForUsers")
    @ResponseWrapper(localName = "doAllCardReconForUsersResponse", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.DoAllCardReconForUsersResponse")
    public String doAllCardReconForUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param username
     * @param paramdata
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "doPhoneCardRecon", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.DoPhoneCardRecon")
    @ResponseWrapper(localName = "doPhoneCardReconResponse", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.DoPhoneCardReconResponse")
    public String doPhoneCardRecon(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "paramdata", targetNamespace = "")
        String paramdata);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doAllCardRecon", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.DoAllCardRecon")
    @ResponseWrapper(localName = "doAllCardReconResponse", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.DoAllCardReconResponse")
    public String doAllCardRecon(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAllCardAmount", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.SearchAllCardAmount")
    @ResponseWrapper(localName = "searchAllCardAmountResponse", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.SearchAllCardAmountResponse")
    public String searchAllCardAmount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param username
     * @param paramdata
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "searchPhoneAmount", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.SearchPhoneAmount")
    @ResponseWrapper(localName = "searchPhoneAmountResponse", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.SearchPhoneAmountResponse")
    public String searchPhoneAmount(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "paramdata", targetNamespace = "")
        String paramdata);

    /**
     * 
     * @param signdata
     * @param username
     * @param imgtype
     * @param paramdata
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "doAllCardReconforPhone", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.DoAllCardReconforPhone")
    @ResponseWrapper(localName = "doAllCardReconforPhoneResponse", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.DoAllCardReconforPhoneResponse")
    public String doAllCardReconforPhone(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "paramdata", targetNamespace = "")
        String paramdata,
        @WebParam(name = "signdata", targetNamespace = "")
        String signdata,
        @WebParam(name = "imgtype", targetNamespace = "")
        String imgtype);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://webservice.wintone.com/", className = "com.ccf.mypackage.GetVersionResponse")
    public String getVersion();

}
