
package com.ccf.mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CardImgreconImplService", targetNamespace = "http://webservice.wintone.com/", wsdlLocation = "http://115.28.166.97:8888/cxfServerX/ImgReconCard?wsdl")
public class CardImgreconImplService
    extends Service
{

    private final static URL CARDIMGRECONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARDIMGRECONIMPLSERVICE_EXCEPTION;
    private final static QName CARDIMGRECONIMPLSERVICE_QNAME = new QName("http://webservice.wintone.com/", "CardImgreconImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://115.28.166.97:8888/cxfServerX/ImgReconCard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDIMGRECONIMPLSERVICE_WSDL_LOCATION = url;
        CARDIMGRECONIMPLSERVICE_EXCEPTION = e;
    }

    public CardImgreconImplService() {
        super(__getWsdlLocation(), CARDIMGRECONIMPLSERVICE_QNAME);
    }

    public CardImgreconImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDIMGRECONIMPLSERVICE_QNAME, features);
    }

    public CardImgreconImplService(URL wsdlLocation) {
        super(wsdlLocation, CARDIMGRECONIMPLSERVICE_QNAME);
    }

    public CardImgreconImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDIMGRECONIMPLSERVICE_QNAME, features);
    }

    public CardImgreconImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardImgreconImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CardImgrecon
     */
    @WebEndpoint(name = "CardImgreconImplPort")
    public CardImgrecon getCardImgreconImplPort() {
        return super.getPort(new QName("http://webservice.wintone.com/", "CardImgreconImplPort"), CardImgrecon.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardImgrecon
     */
    @WebEndpoint(name = "CardImgreconImplPort")
    public CardImgrecon getCardImgreconImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.wintone.com/", "CardImgreconImplPort"), CardImgrecon.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDIMGRECONIMPLSERVICE_EXCEPTION!= null) {
            throw CARDIMGRECONIMPLSERVICE_EXCEPTION;
        }
        return CARDIMGRECONIMPLSERVICE_WSDL_LOCATION;
    }

}
